### ISSUE TITLE
xarray integration

### ISSUE THREAD

**Issue by ar4** [equinor/segyio#111]
It seems to me like segio and [xarray](https://github.com/pydata/xarray) are a good match for each other. If segyio was reimplemented to be an i/o backend for xarray, I think the existing features, such as being able to access slices of data and lazy loading of data, would be retained, while additional benefits of xarray, such as easy integration with dask, would also be available. I imagine that it would require a large rewrite of segyio, and so is probably not possible, but it seems like such an appealing idea that I thought I would still propose it for consideration.

**Comment by pgdr** [comment]
Thanks for the issue and the idea, I'm sure it's a good one.

Could you quickly summarise what xarray is and the main reasons you'd like an xarray frontend for SEG-Y?

What functionality from xarray would you like to apply on SEG-Y files?

**Comment by ar4** [comment]
xarray is like [Pandas](http://pandas.pydata.org/) for multidimensional arrays, and is particularly useful for very large ones. It attaches coordinates and attributes to numpy arrays. It allows you to apply much of the useful Pandas functionality to multidimensional arrays, such as very convenient indexing operations. It supports lazy loading, and works well with [dask](http://dask.pydata.org/) (including, recently, dask distributed). This means that you can very easily open a large file, such as a prestack SEG-Y, across multiple nodes on a cluster, and have the appropriate blocks of data loaded when needed onto the appropriate nodes for processing. I think all of these would be useful when working with SEG-Y files.

**Comment by ar4** [comment]
I wrote [a little tool to convert SEG-Y to NetCDF](https://github.com/ar4/netcdf_segy) so that xarray can be used. It currently uses SegyIO to read the SEG-Y. I also wrote [a notebook that includes a demonstration](https://github.com/ar4/netcdf_segy/blob/master/notebooks/netcdf_segy.ipynb).

**Comment by jokva** [comment]
This is *amazing* work. Would you mind if we included a reference to this in the readme, with a link to your project?

**Comment by ar4** [comment]
I am glad that you like it. You may certainly include a reference.

**Comment by jokva** [comment]
@ar4 I just submitted the reference https://github.com/Statoil/SegyIO/pull/129

If you like it we'll merge it as is, if there's something you'd like to redact or add, let us know. And thanks again for your contribution.

**Comment by ar4** [comment]
Thank you for the kind words. They perhaps oversell it a bit, though. The tool only converts SEG-Y files to NetCDF format (and does so in what I suspect is an inefficient and non-robust way). The NetCDF files can then be accessed using xarray. An actual xarray backend that directly reads SEG-Y files would be wonderful. At the moment, netcdf_segy is more of a tool to allow a demonstration of how convenient xarray is for working with seismic data (which might encourage someone to create an xarray backend ;-) ).

What do you think of this instead:

```
## Related projects
[Alan Richardson](https://github.com/ar4) has written a little tool that uses SegyIO to convert SEG-Y files to [NetCDF](https://en.wikipedia.org/wiki/NetCDF) format. One advantage of this is that the resulting NetCDF files can be accessed using [xarray](http://xarray.pydata.org), as Alan demos in this [notebook](https://github.com/ar4/netcdf_segy/blob/master/notebooks/netcdf_segy.ipynb).
```

**Comment by ar4** [comment]
[SEGY-SAK](https://github.com/trhallam/segysak) is probably the solution to this issue, so I think we can close it.
