### ISSUE TITLE
Dropping python2.7 support on MSVC

### ISSUE THREAD

**Issue by jokva** [equinor/segyio#223]
Hi everyone,

The python extension is getting some love, and we'd like to upgrade to C++11. Unfortunately, the only supported msvc on Windows is visual c++ 2008, which does not support C++11. I *think* it might be possible to build on mingw, also for 2.7, but the default Windows toolchain with setuptools is the compiler bundled with Python.

If anyone is using segyio with python2.7 on Windows, we'd like to know. If there's no response, we'll move towards C++11 and possibly figure out mingw for 2.7 on Windows.

Thanks!

**Comment by JensGM** [comment]
What about using clang?

**Comment by jokva** [comment]
For compiling on Windows, or compile segyio in general? If it's the latter, segyio has always been clang-compatible.

**Comment by JensGM** [comment]
Just for windows

**Comment by jokva** [comment]
Doable, but then you can't use vanilla setuptools anymore, and I'd like to avoid that. If there's no 2.7 users on Windows, we can drop support altogether, and keep the vanilla setuptools, but use C++11 in the extension.

**Comment by jokva** [comment]
https://github.com/equinor/segyio/pull/384

#384 setuptools, and will allow us to experiment more with compilers. I'm closing this issue now, with the conclusion that python 2 on Windows is not interesting anymore, and if it breaks at some point with upgraded compilers then it will remain broken.

1.8 will be the last series to officially support python 2.7 on Windows.
