### ISSUE TITLE
Is there any plan to put segyio on conda-forge?

### ISSUE THREAD

**Issue by whimian** [equinor/segyio#284]
I am a user of `conda` and `conda-forge`. It will be better if `segyio` could be on `conda-forge`.

**Comment by jokva** [comment]
No concrete plans - it's distributed with both pip and debian. We've yet to package it for any other distributions, linux, brew, conda, or otherwise, but that's mostly from our own needs than anything.

**Comment by jokva** [comment]
https://github.com/conda-forge/segyio-feedstock

For some reason it's not built and uploaded yet, but I've made the recipe.
