### ISSUE TITLE
Petrel does not recognize 3D segy file generated by Segyio

### ISSUE THREAD

**Issue by cliffrunner** [equinor/segyio#338]
Hello,

I am currently using Segyio to write a 3D segy volume. The scripts are as following:

    with segyio.create('test_coarse.sgy', spec) as f:
        # write the line itself to the file and the inline number in all this line's headers
        for ilno in tqdm(spec.ilines):
            f.iline[ilno] = well_data_vol[ilno, :, :]
            _, sourcey = lineTrace2XY(ilno, 1, survey_XY, inline_num, xline_num)
            f.header.iline[ilno] = {
                segyio.TraceField.INLINE_3D: ilno,
                segyio.TraceField.offset: 0,
                segyio.TraceField.SourceY: sourcey
            }

        # then do the same for xlines
        for xlno in tqdm(spec.xlines):
            sourcex, _ = lineTrace2XY(1, xlno, survey_XY, inline_num, xline_num)
            f.header.xline[xlno] = {
                segyio.TraceField.CROSSLINE_3D: xlno,
                #segyio.TraceField.TRACE_SAMPLE_INTERVAL: sample_step,
                segyio.TraceField.SourceX: sourcex
            }

"well_data_vol": a volume I created using well log data, and data points are at each intersection of inline, xline and sample. 
"sourcex" and "sourcey": gives X and Y coord for each trace.

When I tried to use Petrel to visualize the segy volume, it seems there is nothing (and yes, the segy file is couple hundred MBs).  My guess is that there are some parameters I didn't specify correctly. 

Anything would help!

Yao

**Comment by jokva** [comment]
Hi Yao,

I'm not sure what Petrel needs to be able to visualise a segy file, but it might need more metadata both the binary header and trace header than you provide currently. What those fields are I don't know, maybe there's some information on it in the Petrel manual?

Other than that, please also try the latest beta release (`pip install segyio==1.8.0b1`, because there _might_ be a bug there that you've been bitten by.

**Comment by cliffrunner** [comment]
@jokva Thanks for the comments. 
Petrel actually reads in the file without a problem. But the inline, xline and slice don't show anything on 3D window. Also when I check the histogram of this segy volume, there is apparently no data to be shown. 
I will update my segyio and try again.

**Comment by jokva** [comment]
This seems stale - please reopen or make a new issue if this persists.
