### ISSUE TITLE
Reading subset of a trace from t1 to t2 (or z1 to z2)

### ISSUE THREAD

**Issue by mrava87** [equinor/segyio#340]
Hello,
we would like to read a big (eg prestack) data in memory using the segyio.tools.collect(segyfile.trace[:]) routine. However we are only interested in reading a subset of samples (ie time or depth axis) which fits into memory while reading the entire data for all samples does not. One way could be to make a for loop/list comprehension ourselves but this should perform poorer segyio.tools.collect. We wonder if there is a case here to build something to read a subset of a trace like we do for trace, iline, xline, gather?

**Comment by jokva** [comment]
Addressed in #383, at least for reading.
