### ISSUE TITLE
TraceField.SourceX and .SourceY

### ISSUE THREAD

**Issue by cliffrunner** [equinor/segyio#347]
Hello,

The problem I have is that I don't know how to assign x and y for my inline and xlines. Below is my code (a modification from the example 'make_file.py'):
![capture2](https://user-images.githubusercontent.com/41877666/50493646-83351b80-09e4-11e9-819f-847520822569.PNG)
As you can see, when I loop over my inline, I am giving the y coordinate of the 1st xline to SourceY, and when I loop over my xline, I am giving the x coordinate of the 1st xline to SourceX.
When I load the data into Petrel, this is what I get (yellow grids):
![capture](https://user-images.githubusercontent.com/41877666/50493508-9b586b00-09e3-11e9-9fd7-b177994bf58e.PNG)
The correct area should be the light blue grids. 
I tried to uncomment these two lines from the code (# segyio.TraceField.SourceX: sourcex, # segyio.TraceField.SourceY: sourcey), but then Petrel gave error messages.

Any help is appreciated.

**Comment by jokva** [comment]
Hi, and thanks for the detailed report.

First and foremost, what version are you using? We've found a series of bugs when writing headers by lines, and you just might've been bitten by one. You can check in python by printing `segyio.__version__`.

Other than that, your procedure is correct, at least for very small files. We're investigating other causes, but writing stuff by cross-line (or more generally by the _slow_ direction) incurs a VERY heavy performance penalty, on the order of 10-100x slower than doing trace-by-trace.

If you would be so kind, please re-write the loop to just do trace-by-trace writing, manually keeping track of in/crossline and sourceX/Y, and see if the problem persists.

**Comment by cliffrunner** [comment]
I am using segyio 1.8.0b1. I believe that is the latest one. For now I am using the trace-by-trace method and it works for now. But it would be very nice if the inline writing part could work. 
Another suggestion I have is that to provide a detailed example of how to create a segy file (not just attributes at each trace but also to assign X and Y) will be really helpful. Segyio is a very powerful tool, but I struggled for a while to figure out how to use it since there is not much instruction online. 
I can contribute my example if that works for you.

**Comment by jokva** [comment]
The latest is 1.8.3, but all relevant fixes should be in 1.8.0b1 too.

> But it would be very nice if the inline writing part could work.

It _should_, and this is a bug.

> Another suggestion I have is that to provide a detailed example of how to create a segy file (not just attributes at each trace but also to assign X and Y)

Yes, we need more good examples like that (some are in the works, some more documentation improvements are planned). However, assigning X and Y like you're talking about _is_ writing attributes to each trace.

> I can contribute my example if that works for you

That would be very helpful, thanks!

**Comment by ErlendHaa** [comment]
Hi
I've looked at your code and from what I can see the results you are getting (the yellow grid) is what I would expect you to get based on the code. Note that I've made the assumption that the axis of the petrel figure is aligned with the x and y axis for the coordinates you're assigning to SoruceX/SourceY. Let me know if that is not the case.

Basically the line: `f.header.iline[ilno] = { segyio.TraceField.SourceY: sourcey } ` assign the value sourcey to _all_ traces that is a part of `inline[ilno]`. The same goes for the sourcex assignments. I'll give you an example to clearify:

```
spec.ilines = [10,11,12]
spec.xlines = [20,21,22]
spec.sorting = Segyio.TraceSortingFormat.INLINE_SORTING

sourcex = [100, 200, 300]
sourcey = [150, 250, 350]

for index, ilno in enumerate(spec.ilines):
    f.header.iline[ilno] = { Segyio.TraceField.SourceY : sourcey[index] }

for index, xlno, in enumerate(spec.xlines):
     f.header.iline[ilno] = { Segyio.TraceField.SourceX : sourcex[index] }

# print the value of sourcex/sourcey from each header
print("SourceX: {}".format( f.attribute( Segyio.TraceField.SourceX )[:] ))
print("SourceY: {}".format( f.attribute( Segyio.TraceField.SourceY )[:] ))
```
This outputs:
`SourceX: [100, 200, 300, 100, 200, 300, 100, 200, 300]`
`SourceY: [150, 150, 150, 250, 250, 250, 350, 350, 350]`

which is expected.

> But it would be very nice if the inline writing part could work

As I've mentioned already, the intention of `f.header.iline[]` is to assign the _same_ value to all trace headers that are a part of the inline `iline[ilno]`. So, in the case of the blue grid it makes no sense to write sourcex/sourcey line by line, as these values are clearly not the same for each trace in a line.  That is, if my assumption of the petrel figure holds.

>I tried to uncomment these two lines from the code (# segyio.TraceField.SourceX: sourcex, # segyio.TraceField.SourceY: sourcey), but then Petrel gave error messages.

Note that if you write sourcex and sourcey in both loops the second loop will overwrite the changes from the first loop as you are assigning new values to the same attributes twice

I hope this clarifies things for you, and don't hesitate to ask if something is still unclear!

> I can contribute my example if that works for you

As you correctly pointed out, there is a lack of good examples so it would be very helpful if you would like to contribute your working trace by trace example

**Comment by hassan-sabirin** [comment]
Just did a couple of test on my end and verified SourceX and SourceY working perfectly.
Instead of doing the two loops above (in which the latter loop will overwrite the earlier values) in @cliffrunner  code, something like below should be performed:
```

for i in range( len(f.header) ):
    ilno = f.header[i][ segyio.TraceField.INLINE_3D ]
    xlno = f.header[i][ segyio.TraceField.CROSSLINE_3D ]
    sourcex, sourcey = lineTrace2XY(ilno, xlno, survey_coordinates, inlines, xlines)
    f.header[i] = {segyio.TraceField.SourceX: sourcex, segyio.TraceField.SourceY: sourcey}
  
```

**Comment by jokva** [comment]
Thanks, Hassan, for the independent verification. I'll consider this solved, then.

@cliffrunner Thanks for the report - hopefully small changes to your code makes segyio work for you. Please reopen or create a new issue if you still have similar problems.
