### ISSUE TITLE
Support for more numerical formats

### ISSUE THREAD

**Issue by jokva** [equinor/segyio#353]
Segyio could quite easily support several of the numerical formats introduced with SEG-Y rev2. Among them are 8-byte integer and 8-byte IEEE float.

**Comment by Khalilsqu** [comment]
> Just to verify, what's the value in bytes 3225-3226 in the binary header?

I am not sure how to get this value, but here is what SeiSee shows me 

Text Header
![image](https://user-images.githubusercontent.com/22060413/53037464-30bb2d00-3472-11e9-99b1-010cc152a920.png)

Bin Header
![image](https://user-images.githubusercontent.com/22060413/53037491-429cd000-3472-11e9-8b73-8e3e78276ea3.png)

Thank you for this great module.

**Comment by jokva** [comment]
Interesting. Your text header says 8 bits (Data sample format code = 6 in 25-26), but the code is used in revision 2 for 8 _bytes_. It's probably some vendor-specific 1-byte integer thing. In revision 2, the numerical value 8 means what this file uses 6 for.

Currently there's no simple way to override whatever is there, but the core library supports it. You can manually do some of the open procedure (I can guide you if you need to), or you can wait for library support.

**Comment by Khalilsqu** [comment]
I think the reason probably is due to the fact the segy file is a merged cube of 3 different seismic cubes. I can read other files. 

Thank you very much, I appreciate your help, this library is already a great help for me. I think I can wait.

**Comment by jokva** [comment]
I'm glad it's helpful.

**Comment by hassan-sabirin** [comment]
Some preliminary work done [here](https://github.com/hassan-sabirin/SegyIO/commit/863cd38fb6da65c4271b30394be80ef8c750c777). Would be great if some segy files with the relevant numerical formats could be provided for testing.

**Comment by hassan-sabirin** [comment]
Here is a sample collection of SEG-Y output, including newer SEG-Y rev2 formats.
[multi-formats.zip](https://github.com/equinor/segyio/files/2914204/multi-formats.zip)


I don't have access to the most modern SEG-Y viewer, but looking at the hex/binary values they seem to be written in the right order. 

If you know of a SEG-Y viewer that supports the newer formats, please load each of them and compare to the default format (Format 1). They should look the same except for some clipped values when the source numerical range has exceeded the target format capacity.


The file numbering correspond to:

-  SEGY_IBM_FLOAT_4_BYTE = 1,
-  SEGY_SIGNED_INTEGER_4_BYTE = 2,
-  SEGY_SIGNED_SHORT_2_BYTE = 3,
-  SEGY_IEEE_FLOAT_4_BYTE = 5,
-  SEGY_IEEE_FLOAT_8_BYTE = 6,
-  SEGY_SIGNED_CHAR_1_BYTE = 8,
-  SEGY_SIGNED_INTEGER_8_BYTE = 9,
-  SEGY_UNSIGNED_INTEGER_4_BYTE = 10,
-  SEGY_UNSIGNED_SHORT_2_BYTE = 11,
-  SEGY_UNSIGNED_INTEGER_8_BYTE = 12,
-  SEGY_UNSIGNED_CHAR_1_BYTE = 16

lsb =  little endian
msb = big endian

3 bytes numerical format are not yet being handled at the moment.

**Comment by jokva** [comment]
Wait, does this mean we can use these files in our test suite? Where do they come from?

**Comment by hassan-sabirin** [comment]
I generated them from small.sgy, part of the test suite. Feel free to use, but no guarantees. I saw in some cases some formats failed to be terminated properly with 2 bytes missing. I suspect some code path has some bugs, but not sure where yet.

**Comment by jokva** [comment]
Ok, that's nice. That's how most of the data is created - however, without external verification we can only observe that the output is what segyio writes, not that segyio writes it correctly. Looking at the hex takes you 90% of the way there, I suppose.

**Comment by hassan-sabirin** [comment]
I have most of the formats done, but there is a bug when writing any non-word-aligned format, e.g. 1, 2 and possibly 3 bytes. The last blank bytes are never written out. So for 1 byte sized format, 3 bytes will be missing at the end of the output ( 4 bytes - N ). Not sure if they're worth pursuing at the moment, unless many users start to complain. It might take a while to hunt it down.

**Comment by jokva** [comment]
Hi Hassan. Are these changes on your fork? I can fetch them and see if I can figure something out, and maybe wrap it up into a patch we can merge.

**Comment by hassan-sabirin** [comment]
Hi jokva. All code available there now.
If you'd like to test it here are the latest test formats (added missing bytes manually). There is a script that run on these under python/test. You can also inspect these files using a hex editor to verify the bytes. 
[multiformats.zip](https://github.com/equinor/segyio/files/2922617/multiformats.zip)

When I generated them, I didn't do clipping or scaling, so conversion to unsigned format will produce large numbers (signed ints written as is, read as unsigned int).

**Comment by hassan-sabirin** [comment]
I added some unit tests for 1,2,4 and 8 bytes formats. This will generate the converted formats automatically, then compare the values between original and converted. All formats supported by SeiSee can be opened directly.

Found the reason for this issue:
> I have most of the formats done, but there is a bug when writing any non-word-aligned format, e.g. 1, 2 and possibly 3 bytes. The last blank bytes are never written out. So for 1 byte sized format, 3 bytes will be missing at the end of the output ( 4 bytes - N ). Not sure if they're worth pursuing at the moment, unless many users start to complain. It might take a while to hunt it down.
Always call segy_set_format on a freshly opened file whether for reading or writing. Otherwise elemsize (size of trace in bytes) will always be 4 regardless of the actual format size.

**Comment by jokva** [comment]
> Always call segy_set_format on a freshly opened file whether for reading or writing. Otherwise elemsize (size of trace in bytes) will always be 4 regardless of the actual format size.

This is actually expected behaviour, and Python code paths should always do this. It's easy to miss in C++ though.

**Comment by jokva** [comment]
... and that exact bug is in segyio.create, for non-4-byte formats. I'll get a fix out asap.

**Comment by hassan-sabirin** [comment]
3-byte formats will need a different way of writing the traces, as each sample is not word-aligned. It doesn't seem important at the moment so I am not doing anything about this.

**Comment by jokva** [comment]
https://github.com/equinor/segyio/pull/358 This fixes the create-issue for non-4-byte formats.

**Comment by jokva** [comment]
Indeed, and numpy doesn't support 3-byte ints without manually splitting them and re-assembling them. I guess if we're to support 3-byte ints we should rather promote to 4-byte and do the conversion internally, but that's a much larger change. Until someone asks for it it will remain unimplemented.

**Comment by jokva** [comment]
@hassan-sabirin I pulled your changes, fixed some minor stuff and re-generated the test files from your test suite with the fixed segyio.create.

I didn't pull your scenarios where you open f3 and write them as various formats yet, as they're somewhat repetitive and I'm not certain they add any value. If you feel otherwise, and submit a PR, we'll for sure consider merging them, after maybe some discussion.

Thank you very much for quite the valuable contribution.

**Comment by hassan-sabirin** [comment]
@jokva I guess the value for me is I could compare and check that the value I am reading from the original format is the same as what I am reading in the converted format, using the exact same process/function sequence. 

Secondly, I could compare the SEG-Y output compatible with SeiSee ( 4-byte int ), then with a hex editor and check the trace byte sequence, then confirm it's the same pattern in 1,2 and 8 bytes. I could repeat the same process with signed, unsigned, little and big endian formats.

In the test scenarios to unsigned formats, I performed some scaling to normalise the values. The end part of each test validates the values, and then one could check it in other loaders that the same values appear.

It might not be a fully automated process, but they helped me in verifying a consistent read/write pattern for all formats.

**Comment by jokva** [comment]
> @jokva I guess the value for me is I could compare and check that the value I am reading from the original format is the same as what I am reading in the converted format, using the exact same process/function sequence.

This is what's done in the f3_in_format function though, but a little bit more concise. Do you think anything's insufficiently covered by only using this approach?
