### ISSUE TITLE
Overwrite trace header with csv file

### ISSUE THREAD

**Issue by ccamos** [equinor/segyio#356]
I'm trying to calculate a few volume attributes, and to do so I need to reference values specific to each trace (in this case, surface TWT and amplitude). My plan was to store these values in insignificant trace header locations and access the values as "constants" for each trace. I have a .csv file with inline, crossline, junk, and data of interest. The plan was to cross reference the .csv file to my 3D cube based on IL/XL, and then use the data of interest from that row to write into the header of that specific trace. I'm having a bit of trouble with the code, and would appreciate any suggestions. Here is what I have so far:

Example of my csv data, first column is IL, second column is XL, fifth column is the data I would like to write into the header
```
input_horz = open('C:\\Users\\User\\Desktop\\Radar\\SEGY\\Horizons\\Surface_3D_edit.csv', 'r')
threeD_horz = np.loadtxt(input_horz,delimiter=",")
print(threeD_horz.shape)
print(threeD_horz[0])
(251001, 5)
[1.850000e+03 2.500000e+03 1.595525e+06 1.904275e+06 1.191443e+03]
```
Checking data in my files, I plan on overwriting the "DataUse" header
```
with segyio.open(segycopy3D, "r") as segyfile:
    print("Value in header to overwrite:", segyfile.header[100][segyio.TraceField.DataUse])
    print("Inline value at trace:", segyfile.header[100][segyio.TraceField.INLINE_3D])
    print("Inlines from csv:", threeD_horz[:,0])
    print("Xlines from csv:", threeD_horz[:,1])
    print("TWT from csv:", threeD_horz[:,4])
Value in header to overwrite: 0
Inline value at trace: 1850
Inlines from csv: [1850. 1850. 1850. ... 2350. 2350. 2350.]
Xlines from csv: [2500. 2501. 2502. ... 2998. 2999. 3000.]
TWT from csv: [1191.443 1191.375 1191.243 ... 1142.52  1143.059 1143.292]
```
How I've started the code to overwrite the "DataUse" header, but got stuck
```
with segyio.open(segycopy3D, "r+") as segycopy:
    for x in segycopy.header[:]:
        if segycopy.header[x][segyio.TraceField.INLINE_3D] == threeD_horz[:,0]:   #first column of csv is inlines
            if segycopy.header[x][segyio.TraceField.CROSSLINE_3D] == threeD_horz[:,1]:   #second column of csv is xlines
                x.update({segycopy.TraceField.DataUse: threeD_horz[:,4]})   #how to reference proper location in 5th column of csv?
print(segycopy.header[100][segyio.TraceField.DataUse])

TypeError                                 Traceback (most recent call last)
<ipython-input-25-6cae758bec23> in <module>
      2 with segyio.open(segycopy3D, "r+") as segycopy:
      3     for x in segycopy.header[:]:
----> 4         if segycopy.header[x][segyio.TraceField.INLINE_3D] == threeD_horz[:,0]:   #first column of csv is inlines
      5             if segycopy.header[x][segyio.TraceField.CROSSLINE_3D] == threeD_horz[:,1]:   #second column of csv is xlines
      6                 x.update({segycopy.TraceField.DataUse: threeD_horz[:,4]})   #how to reference proper location in 5th column of csv?

TypeError: 'generator' object is not subscriptable
```

**Comment by ccamos** [comment]
So I have at least gotten through several errors, but the code I landed on does not seem feasible due to inefficiency. To get around ```TypeError: 'generator' object is not subscriptable``` messages I used lists based on my trace count (251001), but this leads to far too much iteration

Any guidance on a better approach would be appreciated:

```
with segyio.open(segycopy3D, "r+") as segycopy:
    for x in segycopy.header[:]:
        y = list(range(251001))
        z = list(range(251001))
        for i in y:
            for k in z:
                if segycopy.header[i][segyio.TraceField.INLINE_3D] == threeD_horz[k,0] and segycopy.header[i][segyio.TraceField.CROSSLINE_3D] == threeD_horz[k,1]:   
                    x.update({segyio.TraceField.DataUse: int(threeD_horz[k,5])})
```

**Comment by jokva** [comment]
Hi ccamos,

I'll get back to you in a few hours, is that alright?

**Comment by ccamos** [comment]
Absolutely. As a latest update I think I eliminated one iteration loop, but the code is still running so I can't check the output for correctness yet:

```
with segyio.open(segycopy3D, "r+") as segycopy:
    for x in segycopy.header[:]:
        z = list(range(251001))
        for k in z:
            if threeD_horz[k,0] == [segyio.TraceField.INLINE_3D] and threeD_horz[k,1] == [segyio.TraceField.CROSSLINE_3D]:   
                x.update({segyio.TraceField.DataUse: int(threeD_horz[k,5])})
```

**Comment by jokva** [comment]
Ok, I _think_ I understand your problem.

First of all, when you do `for x in f.header[:]`, the `x` _is_ the header, not the index. Additionally, headers by default, unlike traces, have reference semantics, so you can update a header in-place and it will work as expected.

To your problem: Right now, you loop through your full CSV every time in order to detect when to update a trace header, but presumably there will only ever be one row per il/xl, right? If so, you gain a _lot_ by actually building an index once, then look-up into that.

Essentially, this is what you want to do:

```
horizon = {}
for ln in threeD_horz:
    horizon[(in[0], in[1]) = in[4]

coords = itertools.product(f.ilines, f.xlines)
for i, coord in enumerate(coords):
    header[i][segyio.TraceField.DataUse] = horizon[coord]
```

This assumes your file is inline sorted.

**Comment by ccamos** [comment]
Thanks for the feedback. Yes, there should only be ONE il/xl row in the csv that matches the trace header, and constantly looping through the csv for every trace seemed very inefficient (code was running over 2 hours for my 1 GB file before I killed it). Yes, my csv file is inline sorted.

I used your suggestion, and the code ran extraordinarily fast (almost instantly). Below is the code I used with a few prints added in:

```
with segyio.open(segycopy3D, "r") as segycopy:
    print(segycopy.header[50][segyio.TraceField.DataUse])

horizon = {}
print(threeD_horz[50])
for ln in threeD_horz:
    horizon[(ln[0], ln[1])] = ln[5]
    
with segyio.open(segycopy3D, "r+") as segycopy:
    coords = itertools.product(segycopy.ilines, segycopy.xlines)
    for i, coord in enumerate(coords):
        segycopy.header[i][segyio.TraceField.DataUse] = int(horizon[coord])

with segyio.open(segycopy3D, "r") as segycopy:
    print(segycopy.header[50][segyio.TraceField.DataUse])


0
[1.850000e+03 2.550000e+03 1.595525e+06 1.928025e+06 1.188843e+03
 1.188843e+06]
9195
```


The first printed ```0``` shows that the "DataUse" trace header starts as a 0. The next printed output shows the 6 columns in the csv file. I added the 6th row so that I could turn the TWT into an integer (error message stated integer was required) and not lose the decimal places. In this line, the last value of ```1.188843e+06``` is the TWT value I would like to write into the header. The last print statement shows that the "DataUse" trace header is now ```9195```. This is already great progress, but I can't quite sort out where the 9195 came from.

**Comment by jokva** [comment]
Let me check, my guess is that the size of the `DataUse` is too small for your relatively large values.

**Comment by jokva** [comment]
Looks like it. DataUse is only 2 bytes long, but 1.19e06 requires 4 bytes to be accurately represented. Either use a larger header word, or scale your values somehow.

**Comment by ccamos** [comment]
Good spot. I just tried it with a 4 byte header and it worked perfectly. Thanks again!

**Comment by jokva** [comment]
Any time. I presume this is now resolved, so I'll close the issue.
