### ISSUE TITLE
Run (and fix) errors reported by asan

### ISSUE THREAD

**Issue by jokva** [equinor/segyio#357]
Building segyio with -fsanitize=address,undefined shows some errors (from the test suite, so probably a faulty test). Regardless, it's something that should be both tested and fixed properly.

**Comment by hassan-sabirin** [comment]
I encountered several exceptions running the test suite myself. Not sure if they are related to ASAN.

**Worth checking:**
- Run-Time Check Failure #2 - Stack around the variable 'val' was corrupted.
SCENARIO( "reading a 2-byte int file", "[c.segy][2-byte]" ) in segy.cpp
Removing the whole scenario from the test suite clears the error

**Less serious / supposed to throw exceptions:**
source: TEST_CASE( "unstructured throws on non-existing paths", "[c++]" )  in segyio-cpp.cpp, segyio.hpp line 1025
- exception: std::runtime_error at memory location 0x013AEC84.

source: TEST_CASE( "bounds-checked throws on out-of-range trace access", "[c++]" ), segyio.hpp line 1224,1218
- exception: std::out_of_range at memory location 0x013AEB7C.
- exception: std::out_of_range at memory location 0x013AEB7C.
- exception: std::out_of_range at memory location 0x013AEB88.

This is on fresh copy from this repo (not including my own changes)

**Comment by jokva** [comment]
I picked up the first one, not sure about the rest (gcc 6.3 on debian). The rest might be legitimate errors too.

**Comment by hassan-sabirin** [comment]
I don't think [this part](https://github.com/equinor/segyio/blob/f67e2180e6c64aa1378ec722a934d75aa2ee75d7/lib/test/segy.cpp#L1428) is right. Second arg should be samplecount=1 instead of byte size.

**Comment by jokva** [comment]
That seems to be correct indeed.

**Comment by jokva** [comment]
#360 fixes this, at least.

**Comment by ShikhaMishra9** [comment]
Hi Hassan,

We did some sanitary checks and could not find any further errors.
Can you please check once again , if you are getting any error. Also it would be great if you can share .
