### ISSUE TITLE
Change segy format

### ISSUE THREAD

**Issue by doiko** [equinor/segyio#387]
Hi,
We need to create a duplicate of a segy file with a different number format (ie. original int, new one float32)
We tried to use the scripts in https://segyio.readthedocs.io/en/latest/segyio.html#segyio.create but many times fails, usually when copying the headers (dest.header = src.header)
Is it possible to use a system copy of the original file and then open and change the format (dtype) of the copied one?
Thanks,
Dimitris

**Comment by jokva** [comment]
What fails when you copy the headers? That in itself shouldn't fail, but you need to remember to _update_ the target file's format header. Do you have any error messages you're seeing?

**Comment by doiko** [comment]
The copy code is

**Comment by jokva** [comment]
Interesting, the program looks correct.

Could you please try to do it with indices, i.e.
```
for i in range(len(src.trace)):
    dest.header[i] = src.header[i]
    dest.trace[i] = src.trace[i]
```

**Comment by doiko** [comment]
The same error with 
`    with segyio.open(segy_src, "r") as src:
        spec = segyio.spec()
        spec.sorting = src.sorting
        spec.format = f_format
        spec.samples = src.samples
        spec.ilines = src.ilines
        spec.xlines = src.xlines
        with segyio.create(segy_dest, spec) as dest:
            if copy_text_bin:
                dest.text[0] = src.text[0]
                dest.bin = src.bin
            for i in range(len(src.trace)):
                dest.header[i] = src.header[i]
                dest.trace[i] = src.trace[i]`

**Comment by jokva** [comment]
Wait, hang on, your `f_format` is 3? 3 is 2-byte integers, which is why your traces are too short.

Try with `f_format = 5`

**Comment by doiko** [comment]
But I want to reduce segy size, no reason to have 32bits to store some integers in the range 1:10

**Comment by jokva** [comment]
In the original post, you said you wanted it converted to float.

But ok, if you want to _shrink_ the file that should be equally doable. I'll have a look through some source.

**Comment by jokva** [comment]
What version of segyio are you using? 1.8.x?

**Comment by jokva** [comment]
Also, are you doing `copy_text_bin`? If you do that, but want the format updated, you need to do

`dest.bin.update(format = f_format)` (which you should probably do anyway).

**Comment by doiko** [comment]
Fantastic!
Was using 1.7.1 moved to 1.8.1, added also the dest.bin.update(format = f_format) and works fine.
Thanks for the help.
You can close the ticket.

**Comment by jokva** [comment]
Happy it works!
