### ISSUE TITLE
X-Y Coordinates only as Integers

### ISSUE THREAD

**Issue by ansim58** [equinor/segyio#389]
Hi, i want to extract the trace-coordinates from a segy file.
when I open my segy-file in seisee, I find float-numbers for the Source-X and Source-Y coordinates. Sample format is (seisee) IBM Float (32 bit), Big Endian byte order.

When I open the same file via segio (strict=False or ignore_geometry = True) i only get Integers for the 
segyfile.header[1][segyio.TraceField.SourceX] 
segyfile.header[1][segyio.TraceField.SourceY].

So whats my fault? Do you have a hint?
Thank you in advance!!! Andreas

**Comment by jokva** [comment]
All header words in SEG-Y are integers always, so it's not your fault. If seisee shows something else, it's because of an extended data stanza, or something similar.

**Comment by jokva** [comment]
Look at the value in SourceGroupScalar. Multiply your Source X/Y by that (if positive), or divide if negative, and see if the value corresponds to what seisee shows you.

**Comment by ansim58** [comment]
Thank you for answering so quick!
SourceGroupScalar is -100 ;-)
I'll try with this...

**Comment by jokva** [comment]
Any time - I suppose this is now all working well, so I'll close this issue. Please open a new one if you still struggle.
