### ISSUE TITLE
Error in Documentation Example

### ISSUE THREAD

**Issue by JesperDramsch** [equinor/segyio#391]
The documentation for `segyio.tools.collect` states

```python
f = segyio.open('post-stack.sgy')
x = segyio.tools.collect(f.traces[:])
```

This throws the error the `SegyFile` does not face the attribute traces.

**Comment by jokva** [comment]
Thanks, you're absolutely right! We'll patch it right away.

**Comment by jokva** [comment]
https://github.com/equinor/segyio/commit/a4932d2642b4738e9e1eeccb9c56da2944794429

Thank you!

**Comment by JesperDramsch** [comment]
Awesome.
