### ISSUE TITLE
module segyio has no attribute tools

### ISSUE THREAD

**Issue by sumitav** [equinor/segyio#393]

**Comment by sumitav** [comment]
In the segyio documentation,,given a 2d,3d array we can convert that into segy file but while running that script in anaconda or spyder resulting in an error "Module segyio has no attribute tools" however its there.
**Also sometimes not though in spyder but its getting executed in jupyter but most of the time I am getting the same error.
@jokva kindly look into this issue.

**Comment by sumitav** [comment]
**CODE::
import segyio
import numpy as np
filename='test5.sgy'
segyio.tools.from_array2D(filename,synthSeis.astype(np.float32),format=1,dt=2000)

ERROR:
AttributeError                            Traceback (most recent call last)
<ipython-input-16-0a333d3a8508> in <module>()
----> 1 import segyio
      2 import numpy as np
      3 filename='test5.sgy'
      4 segyio.tools.from_array2D(filename,synthSeis.astype(np.float32),format=1,dt=2000)

F:\DA\Seismic\segyio.py in <module>()
      2 import numpy as np
      3 filename='test3.sgy'
----> 4 segyio.tools.from_array3D(filename,synthSeis1.astype(np.float32),iline=321,xline=300,format=1,dt=2000)
      5 #with segyio.open( filename, "r+" ) as src:

AttributeError: module 'segyio' has no attribute 'tools'**

**Comment by sumitav** [comment]
**@jokva @IvanKolesarEquinor  Kindly look into this issue.**

**Comment by hassan-sabirin** [comment]
Are you sure you have it setup properly ?  What is the output of print (segyio.__version__) ?
Works here on Spyder and Jupyter, segyio 1.8.6, Python 3.7.1 32-bit Windows 10.

**Comment by sumitav** [comment]
Yes have setted up properly..python version-3.7,1 64-bit windows 8.1 pro

**Comment by sumitav** [comment]
kindly help @hassan-sabirin @IvanKolesarEquinor

**Comment by hassan-sabirin** [comment]
I suspect it's not loading the DLL properly, either due to 32 vs 64-bit mismatch, or due to invalid path. Can you reinstall using pip and tell us which file (.whl) it's installing ?

**Comment by sumitav** [comment]
C:\Users\lenovo>pip install segyio
Collecting segyio
  Using cached https://files.pythonhosted.org/packages/30/0d/4814556c9324af5cf5d
f34be0909ce34b081206b890428e9b460dce43b2d/**segyio-1.8.6-cp35-cp35m-win_amd64.whl**

Requirement already satisfied: numpy>=1.10 in c:\users\lenovo\anaconda3\lib\site
-packages (from segyio) (1.11.1)
Installing collected packages: segyio
Successfully installed segyio-1.8.6

**check it out and kindly tell what to do next...  @hassan-sabirin

**Comment by sveinung-r** [comment]
Can you check your install path for the tools.py file?

**Comment by jokva** [comment]
We're unable to reproduce, and this really seems like an issue with your installation.
