### ISSUE TITLE
module segyio has no attribute 'tools'

### ISSUE THREAD

**Issue by sumitav** [equinor/segyio#394]
C:\Users\lenovo>pip install segyio
Collecting segyio
Using cached https://files.pythonhosted.org/packages/30/0d/4814556c9324af5cf5d
f34be0909ce34b081206b890428e9b460dce43b2d/segyio-1.8.6-cp35-cp35m-win_amd64.whl

Requirement already satisfied: numpy>=1.10 in c:\users\lenovo\anaconda3\lib\site
-packages (from segyio) (1.11.1)
Installing collected packages: segyio
Successfully installed segyio-1.8.6

**check it out and kindly tell what to do next... @hassan-sabirin @IvanKolesarEquinor

Kindly look into this issue,,still its showing the same error

**Comment by jokva** [comment]
See #393
