### ISSUE TITLE
feature: open sgy as cube and export edited cube

### ISSUE THREAD

**Issue by tiulpin** [equinor/segyio#399]
Hello.

How can I open segyfile as cube, edit this cube, then correctly save the edited cube to *.sgy?
May be it would be good to add this feature to the library.

I tried to do it myself, but then got error while opening my result: inconsistent trace count with my file size

Thanks.

**Comment by jokva** [comment]
What do you mean specifically by editing the cube? What do you change?

**Comment by tiulpin** [comment]
I'm making changes to slices of the cube (removing footprints)

**Comment by jokva** [comment]
So you want to _remove_ traces, is that it?

**Comment by tiulpin** [comment]
No, I don't want to remove traces, sorry for the inconvenience)
Here is what I want to do (for example)
- open *.sgy as a cube
- access each slice of cube, change slices values somehow
- save my new cube to *.sgy.

**Comment by jokva** [comment]
That should be pretty straight-forward, since there's no headers being changed. How exactly are you going about this? Are you doing this in-place, or creating a brand-new file?

**Comment by tiulpin** [comment]
I'm creating a brand-new file

**Comment by jokva** [comment]
How are you doing that? Are you making sure to write all the lines, and write all the headers too?

**Comment by tiulpin** [comment]
That's how I'm doing:
```  
with se.open(a_file) as src:
        # Transform data to cubic view and transpose it for inference
        cube_a = se.tools.cube(a_file).T
        cube_b = []

        for slice_n in range(len(cube_a)):
            a = cube_a[slice_n]
            b = process_slice(a)
            cube_b.append(fake_b)
        # Pack filtered slices for saving later
        cube_b = np.array(cube_b).T
        traces = np.reshape(
            cube_fb, (len(cube_fb) * len(cube_fb[0]), len(cube_fb[0][0]))
        )
        # Save original file metadata
        spec = se.tools.metadata(src)
        # Create a new sgy file
        with se.create(fake_b_file, spec) as dst:
            # Copy all textual headers, including possible extended
            for i in range(1 + src.ext_headers):
                dst.text[i] = src.text[i]
            # Copy the binary header
            dst.bin = src.bin
            # Copy all headers in the new inlines
            dst.header.iline = src.header.iline
            # Copy filtered traces
            dst.trace = traces
```

**Comment by jokva** [comment]
What's the shape of `cube_a` and `traces` in your example?

**Comment by tiulpin** [comment]
`cube_a.shape` is `(1500, 513, 513)` and `traces.shape` is `(65536, 1500)`

**Comment by jokva** [comment]
That's your problem - 513*513 is _much_ larger than 65536. Try updating cube a in-place, and flatten it to `(513*513, 1500)` before giving it to dst.trace.

**Comment by tiulpin** [comment]
Sorry, I gave you the wrong shape before. The issue with the shape is resolved (there was a little bug in my code), thank you for the active help!
By the way, I would like to see some method implementing this functionality in your library.

**Comment by jokva** [comment]
What function, exactly? A copy with a slightly modified sub section?

The problem with that is that the _interface_ to such a function would get very complicated if it were to cover most use cases, to the point of being unusable. SEG-Y comes with a _lot_ of knobs and buttons, and if any assumptions are made it will probably be wrong if most cases.

If you have a suggestion for an interface that would address your issues I'd be happy to consider it.

For what it's worth, your program would be simplier if you first copied the file (with shutils, for example), and then modified said copy in-place.

**Comment by tiulpin** [comment]
Just a method of packing extracted cube back to SEG-Y)

**Comment by jokva** [comment]
Are you aware of the from_array functions in tools?

https://segyio.readthedocs.io/en/latest/segyio.html#segyio.tools.from_array

**Comment by tiulpin** [comment]
Thanks a lot. You can close the issue.
