### ISSUE TITLE
Runtime Error trace count inconsistent with file size, trace lengths possibly of non uniform. But they are of appropriate...

### ISSUE THREAD

**Issue by trunlee** [equinor/segyio#401]
Hi all,

This is my first post requesting help via github so forgive me if not appropriate.

I am trying to read a segy file in and pull the nearest traces and rewrite to a file. All seems to be going well (file is being written without breaking, etc.) until I go to read in the file I created. Here is the code to write my segy file... The trace headers are stored in a dataframe (filteredtraces2), and the amplitude data (data_filter2) is stored as a float 32 numpy array.

		out = Stream() 
		for i in range(len(data_filter2[0])): #data_filter[0]
			data = data_filter2[:,i]
			data = np.require(data, dtype=np.float32)
			trace = Trace(data=data)
			stats = Stats()
			trace.stats.starttime = UTCDateTime()
			if not hasattr(trace.stats, 'segy.trace_header'):
				trace.stats.segy = {}
			trace.stats.segy.trace_header = SEGYTraceHeader()
			trace.stats.segy.trace_header.trace_sequence_number_within_line = filteredtraces2.iloc[i]['TRACE_SEQUENCE_FILE'] # trace number
			trace.stats.segy.trace_header.sample_interval_in_ms_for_this_trace = 0.004
			trace.stats.segy.trace_header.original_field_record_number = filteredtraces2.iloc[i]['FieldRecord'] # shot number
			trace.stats.segy.trace_header.delay_recording_time = 0 # delay record time
			trace.stats.delta = 0.004
			out.append(trace)
			
		out.stats = AttribDict()
		out.stats.textual_file_header = 'Textual Header!'
		out.stats.binary_file_header = SEGYBinaryFileHeader()
		
		print("Stream object before writing...")
		print(out)

		out.write("002A.sgy", format="SEGY", data_encoding=5, byteorder=sys.byteorder)
		print("Stream object after writing. Will have some segy attributes...")
		print(out)

Then I get the error **"RuntimeError: trace count inconsistent with file size, trace lengths possibly of non-uniform"** when I try to read it in using this first "with" line... (note there are lines after this but basically I can't even open the file to get to those other lines)

	with segyio.open('002A.sgy', "r", ignore_geometry=True) as f:
	    # Get basic attributes
		n_traces = f.tracecount
		print('Number of traces:',n_traces)
		sample_rate = segyio.tools.dt(f) / 1000
		print('Rate of sampling',sample_rate)

So I've read that this has something to do with the dtype, encoding of the data. I am able to read the file using other methods.
for example using the bit of code provided here: https://github.com/equinor/segyio/issues/238#issuecomment-373735526 

I am able to see that the file has a consistent/appropriate number of samples, the right number of traces.

Thoughts?

Taylor

**Comment by jokva** [comment]
Hi Taylor,

So I don't know how your writer works or what it does, so I'll for now treat it like a black box.

This particular error happens because segyio assumes all traces have the same number of samples, and all traces in the same format. This means that `tracecount * samples * size-of-sample + space-of-headers == size-of-file`.

One of these are now wrong. It could be that you're writing in little-endian as you would, but I doubt you're telling segyio. Try passing `endian = 'little'` to segyio.open

**Comment by trunlee** [comment]
Jokva,

Thanks so much. I think I am writing little-endian. Appreciate all the help. 

Taylor
