### ISSUE TITLE
Wiggle plots

### ISSUE THREAD

**Issue by emilsonpl** [equinor/segyio#402]
Dear users/developers of segyio:

What would be the best way to plot wiggle traces from traces retrieved from a file using segyio.open? I am used to Seislab package for Matlab, where we have the s_wplot function that does this job. I wonder if there is something similar written within segyio/Python.

Thank you!

**Comment by jokva** [comment]
Hi,

segyio doesn't come with any built-in visualisation, and it's never been the project's goal. There are a few general-purpose plotting libraries for python out there, but I'm personally not aware of something dedicated for traces.

At the end of the day, though, the traces are just arrays of floating point numbers, and it shouldn't matter if it's segyio that provides them or not.

Maybe some other users can chime in if they know of any seismic-oriented plotting functionality, but for what it's worth I found this: https://stackoverflow.com/questions/33651243/plotting-seismic-wiggle-traces-using-matplotlib
