### ISSUE TITLE
Reading/writing SoureWaterDepth as 2- instead of expected 4-byte integer

### ISSUE THREAD

**Issue by roelanddeheld** [equinor/segyio#405]
The Tracefield.SourceWaterDepths header originating from a seg-y trace header in byte 61-64 seems to be read by segyio as a 2-byte integer instead of a 4-byte integer as expected. For the same input seg-y segyio gives zeroes for water depths whereas obspy does read them.

Not sure if this is an error, or if I am missing something. More in general: is there an option to control how a certain header is read?

**Comment by jokva** [comment]
It is absolutely an error - source water depth is 4 byte, but it was recorded as 2-byte. I'll release a fix right away.

**Comment by jokva** [comment]
Thanks for the report - you were right!

It's fixed and a part of the 1.8.7 release https://github.com/equinor/segyio/releases/tag/1.8.7
