### ISSUE TITLE
Can not open SEGY with long traces

### ISSUE THREAD

**Issue by kurddt** [equinor/segyio#407]
I tried to open a file with traces of 60000 samples each and I got the following error: `RuntimeError: trace count inconsistent with file size, trace lengths possibly of non-uniform`

After some debug I found out that it's because the "Number of expected samples per trace" is read as a signed 16 bit value. Is there any reason for that ?

I understand that the SEGY standard does not explicitly mention that this field is unsigned but a negative number of sample per trace does not really make sense

**Comment by jokva** [comment]
I'll double check quickly, but I'm pretty certain the standard says explicitly that these numbers are signed twos-complement 16-byte integers.

I'll get back to you.

**Comment by jokva** [comment]
> The values in the Binary File Header are defined as two-byte or four-byte, two's complement integers.

https://seg.org/Portals/0/SEG/News%20and%20Resources/Technical%20Standards/seg_y_rev1.pdf

So they're _supposed_ to be signed. Yes, negative don't make sense, and it _does_ place a hard upper limit on samples-per-trace.

**Comment by jokva** [comment]
I think this is the wrong fix, because now we're _lying_ on potentially broken data. Maybe this could be reported explicitly, and an escape hatch be provided, but interpreting this as unsigned is not the right decision.

**Comment by jokva** [comment]
That's quite interesting indeed, and honestly a pretty weird change.

It makes more sense to do this in segy_samples as in #407, with this particular behaviour documented.

**Comment by kurddt** [comment]
The issue with #408 is that if I do:
`
with segyio.open(f, strict = False, ignore_geometry = True) as segy:
    print(segy.bin)
`
I get this results: 
`
{JobID: 1, LineNumber: 0, ReelNumber: 0, Traces: 60, AuxTraces: 0, Interval: 1000, IntervalOriginal: 1000, Samples: -5536, SamplesOriginal: -5536, Format: 5, EnsembleFold: 1, SortingCode: 1, VerticalSum: 1, SweepFrequencyStart: 0, SweepFrequencyEnd: 0, SweepLength: 0, Sweep: 0, SweepChannel: 0, SweepTaperStart: 0, SweepTaperEnd: 0, Taper: 0, CorrelatedTraces: 1, BinaryGainRecovery: 2, AmplitudeRecovery: 1, MeasurementSystem: 1, ImpulseSignalPolarity: 1, VibratoryPolarity: 0, SEGYRevision: 256, TraceFlag: 1, ExtendedHeaders: 0}
`

with #409 :
`
{JobID: 1, LineNumber: 0, ReelNumber: 0, Traces: 60, AuxTraces: 0, Interval: 1000, IntervalOriginal: 1000, Samples: 60000, SamplesOriginal: 60000, Format: 5, EnsembleFold: 1, SortingCode: 1, VerticalSum: 1, SweepFrequencyStart: 0, SweepFrequencyEnd: 0, SweepLength: 0, Sweep: 0, SweepChannel: 0, SweepTaperStart: 0, SweepTaperEnd: 0, Taper: 0, CorrelatedTraces: 1, BinaryGainRecovery: 2, AmplitudeRecovery: 1, MeasurementSystem: 1, ImpulseSignalPolarity: 1, VibratoryPolarity: 0, SEGYRevision: 256, TraceFlag: 1, ExtendedHeaders: 0}
`

**Comment by jokva** [comment]
Sure, but the trace header can be made aware of that too, or even keep a list of headers that should be considered unsigned (in revision 2)

**Comment by kurddt** [comment]
Also in the document, the number of samples per trace in only taken as example so this unsigned behavior could be apply to all fields were it make sense. It's a shame that they didn't specify which fields are signed and which are unsigned

**Comment by kurddt** [comment]
So you would prefer to format the field as unsigned on the python side ?

**Comment by jokva** [comment]
> So you would prefer to format the field as unsigned on the python side ?

Both, in a way. I think the segy_samples can be considered _correct_ in #408 after rev2, assuming it's documented. However, the printing of the header as you demonstrated here should be handled in Python.

**Comment by jokva** [comment]
@kurddt https://github.com/equinor/segyio/pull/413 should fix it in the right place I think, and also fix the returned value by header[k].

There are probably more fields impacted by this that cannot be negative - they will be addressed in a later patch.

Feel free to check it out, and if it works for you!

**Comment by kurddt** [comment]
@jokva Thanks, it seems to work just fine with your changes
