### ISSUE TITLE
Runtime Error trace count inconsistent with file size, trace lengths possibly of non-uniform

### ISSUE THREAD

**Issue by sagarnp007** [equinor/segyio#410]
Hi All,

I am trying to read a segy file using segyio.open(filename), however, I keep getting "_**Runtime Error trace count inconsistent with file size, trace lengths possibly of non-uniform**_"! I have read a few blogs online regarding this issue, but, none of the suggested fixes seem to be working. Any help would be highly appreciated! Thanks in advance!

Regards,
Sagar

**Comment by jokva** [comment]
Hi,

That error means that the file size and the (inferred) number of traces don't correspond. This happens when the file is damaged, or if the traces vary in length.

What do you know about this file, are the traces of variable length?

**Comment by sagarnp007** [comment]
Hi,

Thanks for your reply! Unfortunately, I know nothing about the file. I just received this file and tried importing it and it wouldn't open. I have since tried to change the binaryfileheader, but, while I have been able to get rid of the previous error, the current error is related to the structure and the offsets in the file. Again, since I do not have access to the structure of the file, I wasn't able to resolve the issue.  Do you know of any third party software that one can download that reads a sgy file and converts it to csv? I am asking this as a backup, in case I have to go that route! But, thanks once again for your help and reply!

**Comment by jokva** [comment]
If the file indeed has traces of variable length, there's nothing you can do in the binary header to remedy it.

It could also be that the file is in little-endian - you can try open it with `open(..., endian = 'little')`, and see if it helps. Often, it's useful to get a read of the textual header too for clues.

**Comment by sagarnp007** [comment]
I have tried specifying the endian but to no avail. I have also tried ignoring the shape (assuming the traces of different lengths would render a different shape), but, to no avail. 

I was trying to edit the binary reel header only because I read in one of the blogs that that maybe a possible path forward and although I was able to get rid of the initial error, the one I am getting now is more related to the offsets in the file, which I have no idea about as I have no idea about the file. But, thanks so much for your help!

**Comment by jokva** [comment]
I'm sorry it didn't work out for you. Since it seems there's little we can do, I'll close this issue.

**Comment by GGDRriedel** [comment]
Is there a way of making them readable anyway? Like, I know they might be broken but sometimes I need to at least salvage what's left. 

SEGYDETECTIVE for example reads files that show this error

**Comment by jokva** [comment]
Unfortunately, it is a hard assumption in segyio [1] that traces are always the same length. The C library has some features that you could use to write a custom reader for your file, but segiyo as a project does not support it, I'm afraid.

[1] if segyio2 ever happens, this will be different.

**Comment by Prakhar238** [comment]
Hi, 
I am also getting the same error - "RuntimeError: trace count inconsistent with file size, trace lengths possibly of non-uniform".
I checked my segy file using Seisee software ,for the uniformity in trace lengths . Am pretty sure all traces have number of samples(therefore same trace lengths).  
Can you please explain the other reason for this error? What does this trace count inconsistent with file size mean?
