### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by santaniitr** [equinor/segyio#421]
The Error encountered is from this line......
`from . import _segyio` in the file open.py .... while trying to read a segy data.

OS: Windows 10
Python 3.7.2
segyio 1.8.8 installed using `conda install -c conda-forge segyio`
Visual Studio 2015 is also present in the System

Could it be any msvcp or msvcr.dll missing in my system due to any particular 2013, or 2015 redistributable, from which your "_segyio.pyd" is build ?

**Comment by jokva** [comment]
> Could it be any msvcp or msvcr.dll missing in my system due to any particular 2013, or 2015 redistributable, from which your "_segyio.pyd" is build ?

No, your system should be fine, and this is exactly what conda should provide. Does it not say which DLL it requires and misses?

**Comment by santaniitr** [comment]
No. It does not say anything about which DLL is missing. 

`segyfile = 'File1.sgy'`
`f = segyio.open(segyfile)`

This gives error as..........

Traceback (most recent call last):

  File "ipython-input-7-027554b7428b", line 1, in "module"
    f = segyio.open(segyfile)

  File "C:\Continuum\anaconda3\lib\site-packages\segyio\open.py", line 161, in open
    from . import _segyio

ImportError: DLL load failed: The specified module could not be found.

**Comment by santaniitr** [comment]
Problem solved by installing version 1.9.0a1.
Thanks

**Comment by GGDRriedel** [comment]
I need to reopen this, I am getting the exact same error despite being on 1.9.0
