### ISSUE TITLE
pip install failed on Python 3.8.0 with skbuild not found

### ISSUE THREAD

**Issue by kwinkunks** [equinor/segyio#425]
I realize you might not support Python 3.8 yet, and actually I didn't mean to be using 3.8 in this env (I guess it's conda's default now)... but FWIW, this was a new conda environment containing only jupyter and matplotlib (and their requirements) on Python 3.8.0.

```shell
(geocomp-19) matt@calculus:~/Dropbox/dev/piecewise$ pip install segyio welly bruges
Collecting segyio
  Downloading https://files.pythonhosted.org/packages/d2/1f/22140a1653ea9de382724725af0904203c3c69d76e00f070956444f0b3ef/segyio-1.8.8.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 1.8MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/matt/anaconda3/envs/geocomp-19/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-avnc7gws/segyio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-avnc7gws/segyio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-avnc7gws/segyio/pip-egg-info
         cwd: /tmp/pip-install-avnc7gws/segyio/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-avnc7gws/segyio/setup.py", line 3, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jokva** [comment]
Ok, so you're getting the tarball, because segyio 1.8.8 was never built for python38, because it was either relased before 3.8, or our CI wasn't updated in time. The skbuild thing happens because you're trying to build from source, without all build-time dependencies installed, which is expected behaviour.

**Comment by jokva** [comment]
I'm adding it to the CI now, but in order for the builds to happen, it'd require a new tag. I'll include a bugfix as well so there's some other value added.

In the meantime, please use python3.7, or figure out how to build from source :--------)

**Comment by jokva** [comment]
https://pypi.org/project/segyio/#files

And python 3.8 builds are now available! Thanks for the report, this would've gone on for a _long_ time without it.
