### ISSUE TITLE
 The problem is to read the entire header with all coordinates of the CDP_X CDP_Y seismic trace

### ISSUE THREAD

**Issue by aleran84** [equinor/segyio#428]
import segyio
import numpy as np
import os
directory = 'G:\segy'
files = os.listdir(directory)
i = 0
while (i < len(files)):
    if (files[i].endswith('.sgy')):
        with segyio.open(directory + '/' + files[i],"r") as f:
                CDP_X = f.attributes(segyio.TraceField.CDP_X)[:]
                print(CDP_X)
                CDP_Y = f.attributes(segyio.TraceField.CDP_Y)[:]
                print(CDP_Y)
             
                
        i += 1
    else:
        i += 1

**Comment by jokva** [comment]
What is the problem, exactly?

**Comment by aleran84** [comment]
I need to get the entire list of coordinates CDP_X and CDP_Y from the segy file. The method specified in the script gives only the first and last three coordinates. While in the file (trace) there are 1300

**Comment by jokva** [comment]
Have you tried manually extracting the same fields from `f.header`, or verified your CDPX/Y from other sources? Your code looks fine, and should give you all different CDPX/Y. Can you post the output?

**Comment by aleran84** [comment]
![image](https://user-images.githubusercontent.com/58810484/70711430-97a41e00-1cf2-11ea-97de-85288f21c221.png)

**Comment by jokva** [comment]
Try `np.unique(CDP_Y)`, it looks like a print-abbreviation issue. Or increase the print limit from numpy.

**Comment by aleran84** [comment]
CDP_X = f.attributes(segyio.TraceField.CDP_X)[:]
            **np.unique(print(CDP_X))** 
            CDP_Y = f.attributes(segyio.TraceField.CDP_Y)[:]
            **np.unique(print(CDP_Y))**
========================= RESTART: D:\Pyhton\import.py =========================
[46387610 46387620 46387630 ... 46381910 46381940 46381970]
[824465030 824464870 824464720 ... 824222190 824222040 824221880]
**The result is the same (((**

**Comment by jokva** [comment]
`print(np.unique(CDP_X))`

**Comment by aleran84** [comment]
CDP_X = f.attributes(segyio.TraceField.CDP_X)[:]
            print(np.unique(CDP_X))
            CDP_Y = f.attributes(segyio.TraceField.CDP_Y)[:]
            print(np.unique(CDP_Y))
[46380728 46380732 46380739 ... 46388308 46388309 46388310]
[824221880 824222040 824222190 ... 824464720 824464870 824465030
### **Similarly ...**

**Comment by jokva** [comment]
```
import sys
np.set_printoptions(threshold=sys.maxsize)
```

The problem is that the *print* is truncated.

**Comment by aleran84** [comment]
WORKING !!! A little later I will check the correspondence between the headers and the actual data. I am very grateful to you!

**Comment by jokva** [comment]
Splendid.
