### ISSUE TITLE
Version 1.9.0 reintroduced:  DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by GGDRriedel** [equinor/segyio#435]
Same as in https://github.com/equinor/segyio/issues/421

```
    from segyio import _segyio

ImportError: DLL load failed: The specified module could not be found
```

I am on 1.9.0

**Comment by jokva** [comment]
Are you using conda? Windows?

**Comment by jokva** [comment]
For what it's worth, the segyio.dll _is_ distributed with the conda tarball.

**Comment by jokva** [comment]
And the extension is importable during the build, at least:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=109896&view=logs&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=0d1d4714-3221-52cd-cfdb-f62a891e036b

**Comment by GGDRriedel** [comment]
Yes I am using conda on Windows 7 64 bit Python 3.7.5. 

Oddly enough running it in a dedicated anaconda console works.

It seems to be a spyder 4.0 specific problem as it seems somewhat controversial to run relative imports from submodules. 

More info perhaps here? 
https://stackoverflow.com/questions/16981921/relative-imports-in-python-3

**Comment by jokva** [comment]
Presumably you're launching Spyder from Anaconda too, right?

**Comment by GGDRriedel** [comment]
Yes that is correct. 

I reinstalled the whole env + upgraded to Spyder , the error did not occur again.

**Comment by emblixt** [comment]
Hi
I'm using Python 3.7 on a windows 10 machine, and experience the exact same problem:
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\segyio\open.py", line 161, in open
    from . import _segyio
ImportError: DLL load failed: The specified module could not be found.

Any suggestions on how I can work around this?
Thanks
