### ISSUE TITLE
Text assignment creates no newline

### ISSUE THREAD

**Issue by GGDRriedel** [equinor/segyio#443]
I am writing a new text header through

```
with segyio.open(outfile, "r+",ignore_geometry=True) as out:
    out.text[0]=longtext
```

where longtext is basically "C01 test\n" + "C02 test\n"....

Mot readers(seisee) do not read the EBCDIC header as lines, but rather as a consecutive string and thus the header is displayed incorrectly as one long line

Did I overlook some option in the reader?

**Comment by jokva** [comment]
Hi,

The text interface is not really aware of lines at all, so you need to replace the newlines with the appropriate amount of whitespace. Segyio, like seisee apparently, treats the header as one long string.

**Comment by GGDRriedel** [comment]
It would be nice if it basically reversed the behaviour of segyio.tools.wrap

**Comment by jokva** [comment]
I can see why that would be useful, but I believe it makes more sense to do it outside of segyio.

```>>> text = 'foo\nbar\nbaz\nquux\nplus\n'
>>> ''.join([ln.ljust(80) for ln in text.split()])
'foo                                                                             bar                                                                             baz                                                                             quux                                                                            plus                                                                            '
```

Now this can be assigned to the header, with the behaviour you'd expect.
