### ISSUE TITLE
Depth slice and offsets

### ISSUE THREAD

**Issue by gsakkis** [equinor/segyio#474]
As far as I can tell, the `depth`/`depth_slice` interfaces doesn't support offsets, it works on the default (first) offset.
- Is this indeed the case?
- If yes, is there a fundamental reason for this (e.g. depth doesn't make sense for other offsets) or it just hasn't been implemented?

**Comment by jokva** [comment]
It seems like it is indeed the case, and it simply hasn't been implemented.
