### ISSUE TITLE
I need to open this issue again. Any idea how to work around this?

### ISSUE THREAD

**Issue by TosinJayeola** [equinor/segyio#483]
Hi
I'm using Python 3.7 on a windows 10 machine, segyio v. 1.9.1, and experience the exact same problem:
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\segyio\open.py", line 161, in open
    from . import _segyio
ImportError: DLL load failed: The specified module could not be found.

Any suggestions on how I can work around this?
Thanks

_Originally posted by @emblixt in https://github.com/equinor/segyio/issues/435#issuecomment-673527766_

**Comment by jokva** [comment]
Not really, as I've never really used Windows. How did you install segyio?

**Comment by TosinJayeola** [comment]
I used pip install.

**Comment by jokva** [comment]
Does the 1.9.2 and 1.9.3 builds work for you?

**Comment by jokva** [comment]
Try looking into the C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\segyio dir and check if there's a _segyio.dll in there
