### ISSUE TITLE
pip install 

### ISSUE THREAD

**Issue by krober10nd** [equinor/segyio#485]
Hello, I use `segyio` in my package which is tested on a CircleCI server. Occasionally I receive this issue when the CI server is installing the dependencies.  Historically, I never had to install `skbuild` and it would just work. Seems to have happened recently as well.

```
Collecting segyio
  Downloading segyio-1.9.3.tar.gz (1.1 MB)
     |████████████████████████████████| 1.1 MB 65.8 MB/s eta 0:00:01
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aciz5d_f/segyio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aciz5d_f/segyio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wvhv2k5i
         cwd: /tmp/pip-install-aciz5d_f/segyio/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-aciz5d_f/segyio/setup.py", line 3, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

**Comment by jokva** [comment]
Does your circle job happen to run Python 3.9?

**Comment by krober10nd** [comment]
yup. 

Python 3.9.0

and 

pip 20.2.3 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by jokva** [comment]
Ok. segyio isn't packaged for Python 3.9 yet, so it's trying to build from source. You can maybe force your CI to use python 3.8 for a while, until packages for 3.9 are published.

**Comment by krober10nd** [comment]
switching to a docker with python:3.7.0 fixed the issue.

**Comment by krober10nd** [comment]
Than
