### ISSUE TITLE
Installation_issues

### ISSUE THREAD

**Issue by Simple2bob** [equinor/segyio#501]
Dear equinor,
I recently downloaded the segyio v.1.9.5. But I had a issue to install it. When I installed it, it showed me the following error:

CMake Error at setup-CMakeLists.txt:7 (find_package):
  By not providing "Findsegyio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "segyio", but
  CMake did not find one.

  Could not find a package configuration file provided by "segyio" with any
  of the following names:

    segyioConfig.cmake
    segyio-config.cmake

  Add the installation prefix of "segyio" to CMAKE_PREFIX_PATH or set
  "segyio_DIR" to a directory containing one of the above files.  If "segyio"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:6 (include)

-- Configuring incomplete, errors occurred! 

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\skbuild\setuptools_wrap.py", line 582, in setup
    env = cmkr.configure(cmake_args,
  File "C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\skbuild\cmaker.py", line 229, in configure
    raise SKBuildError(

An error occurred while configuring with CMake.

Could you tell me how to fix this issue. 
Thank you.

**Comment by ejschoen** [comment]
For what it's worth, pip install segyio failed for me in a Python 3.8 venv (on Ubuntu 18.04), but succeeded in a Python 3.7 venv.

**Comment by jokva** [comment]
https://pypi.org/project/segyio/#files

Wheels should be out for python 3.8, but not yet 3.9 which is why it falls back to trying to compile it from source. Until 3.9 images are published you have to use python38.

Installation shouldn't fail on python38, what exactly goes wrong? Is your pip updated?

**Comment by ejschoen** [comment]
Ah. Apologies for the noise.  I saw the same error reported by Simple2bob, but it was due to having an old pip with my python 3.8 environment. 

```pip install --upgrade pip ```

got me 20.3.3 and that works.
