### ISSUE TITLE
Is it possible to use segyio to read SEG-Y files directly in a C++ program?

### ISSUE THREAD

**Issue by ahadji05** [equinor/segyio#504]
Hi segyio team,

I manage to read SEG-Y data in my python applications using your python API, however, I am currently interested in developing similar C++ applications. I am wondering whether segyio is an easy-to-use option for that purpose too.
I haven't seen any documentation on how one could directly extract info from SEG-Y files using a C++-based API.

I would like to hear more about this!

thanks,
Andreas

**Comment by jokva** [comment]
Hi,

Sorry for the late reply.

You can use the C API directly, but it is pretty low-level and does not interpret much for you. There is also an experimental, but unmaintained C++ front that might work for you. It's mostly documented in the headers, and nothing generated like readthedocs.

https://github.com/equinor/segyio/blob/master/lib/experimental/segyio/segyio.hpp
https://github.com/equinor/segyio/blob/master/lib/include/segyio/segy.h
