### ISSUE TITLE
Generators behaving badly?

### ISSUE THREAD

**Issue by da-wad** [equinor/segyio#507]
I've just found a surprise in the way the iline generator is functioning.

Given a slice object with only stop specified I would expect this small program to print `True` twice. But it doesn't...

```python
import numpy as np
import segyio

def test_iline_generator(f, i):
    list_comp = np.asarray([f.iline[i] for i in range(1,i)])
    slicing = np.asarray(list(f.iline[:i:]))
    print(np.array_equal(list_comp, slicing))

f=segyio.open('test-data\\small.sgy')
    
test_iline_generator(f, 3) #True
test_iline_generator(f, 4) #False?!!
```

**Comment by jokva** [comment]
No, it's working as expected - slice is a _generator_, and you're not copying the result before adding it to your list.

```
>>> def test_iline_generator(f, i):
...     list_comp = np.asarray([f.iline[i] for i in range(1,i)])
...     slicing = np.asarray([a.copy() for a in f.iline[:i:]])
...     print(np.array_equal(list_comp, slicing))
... 
>>> test_iline_generator(f, 3)
True
>>> test_iline_generator(f, 4)
```

**Comment by da-wad** [comment]
Riiight, specifically a generator _which yields mutable values_. And the `list()` constructor doesn't do any copying.

But... the first call to my buggy `test_line_generator()` returns True. How so? Because you're [cycling two buffers in the generator](https://github.com/equinor/segyio/blob/a0947881745e8d88dccf1981e60c724a1172a64c/python/segyio/line.py#L234).

Got it. Close?

**Comment by jokva** [comment]
Yea, segyio knows that the generated value should update every step, so as an optimisation it _reuses_ a pair of underlying objects to allocate only twice for loops of any size. This is a _huge_ performance gain in many common scenarios.
