### ISSUE TITLE
install error width Mac M1

### ISSUE THREAD

**Issue by lichuang3698** [equinor/segyio#521]

**Comment by Bersano** [comment]
I think you have to use terminal from rosetta, then it will be successful

**Comment by tasansal** [comment]
I am able to build on M1 Max. I believe this issue is resolved. Here is my build script.

Assuming you're at the source dir of `segyio`:

```shell
PYTHONPATH=<your-interpreter-path>
VIRTUAL_ENV=<your-env-root>

mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$VIRTUAL_ENV -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
make -j10
make install
```

**Comment by tasansal** [comment]
I built wheels for the latest `segyio` 1.9.11 for cpython3.8-3.11 manually and posted them to this PR if anyone wants to use it or upload to PyPI given permission:
https://github.com/equinor/segyio/pull/536#issuecomment-1532280601

**Comment by sebastianvitterso** [comment]
This issue can be closed, as the problem no longer persists @sveinung-r.
