### ISSUE TITLE
Error: when I copy a file with ignore_geometry=True, but shorten all traces

### ISSUE THREAD

**Issue by ReHekat** [equinor/segyio#527]
After copy a file, there is some errors when I open the new file:
       trace count inconsistent with file size, trace lengths possibly of non-uniform
My code：
>>> with segyio.open(srcpath, , ignore_geometry=True) as src:
...     spec = segyio.tools.metadata(src)
...     spec.samples = spec.samples[:len(spec.samples) - 50]
...     with segyio.create(dstpath, spec) as dst:
...         dst.text[0] = src.text[0]
...         dst.bin = src.bin
...         dst.header = src.header
...         dst.trace = src.trace
        file = segyio.open(dstpath, ignore_geometry=True)

**Comment by ErlendHaa** [comment]
Hi,

You slice the `spec.samples`, but not the actual trace. Which creates a mismatch between the metadata and data in the dst file

**Comment by ReHekat** [comment]
> Hi,
> 
> You have update the bin/trace headers when you reduce the number of slices. Have a look here: https://github.com/equinor/segyio/blob/master/python/examples/copy-sub-cube.py

Thanks for your help. It works well,when I insert:
             dst.bin = { segyio.BinField.Samples: len(spec.samples) - 50, segyio.BinField.Traces: src.tracecount }
Maybe the documentation should be modified? [https://segyio.readthedocs.io/en/latest/segyio.html#segyio.create](url)
