### ISSUE TITLE
Cannot Import segy. file

### ISSUE THREAD

**Issue by yshigei** [equinor/segyio#539]
Hello,

I am trying to import .sgy file extracted from Petrel (P-Impedance cube/Post Stack).
segyio.open() successfully worked, but cannot read through inline/xline (segyfile.iline/xline/depth_slice... did not work).

How could I fix this issue??

It would be appreciated if you could help my problem.

Best Regards,
yshig

**Comment by yshigei** [comment]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-34-74a25bda49db> in <module>
      1 # Read data along first xline
----> 2 data = segyfile.xline[segyfile.xlines[1]]
      3 
      4 # Read data along last iline
      5 # data = segyfile.iline[segyfile.ilines[-1]]

c:\Users\shigei\Anaconda3\lib\site-packages\segyio\line.py in __getitem__(self, index)
    204             pass
    205         else:
--> 206             return self.filehandle.getline(head,
    207                                            self.length,
    208                                            self.stride,

OSError: I/O operation on closed file

**Comment by ErlendHaa** [comment]
Your file handle has been closed, before you reach `segyfile.xline[segyfile.xlines[1]]` in your code

**Comment by yshigei** [comment]
Thank you very much @ErlendHaa. 
After fixed my indent as your instruction, it successfully run.
