### ISSUE TITLE
iline xline offset samples

### ISSUE THREAD

**Issue by SherloK1898989** [equinor/segyio#540]
HI , can you please give me a little answer about this parameters 
what the iline ,xline,offset, samples

for to make it more convenient for you , answer with an example , if I have 5 stations , each of which has recorded a date in an array with a length of 2000 , how to write iline ,xline,offset, samples

thank you in advance for the answer I really appreciate it

**Comment by ErlendHaa** [comment]
These are all common terms in seismic. They refer to different directions in the seismic volume.

https://glossary.slb.com/en/terms/i/in-line
https://glossary.slb.com/en/terms/c/crossline

**Comment by SherloK1898989** [comment]
what about spec.samples and traces ?

пн, 24 окт. 2022 г. в 16:30, Erlend Hårstad ***@***.***>:

**Comment by ErlendHaa** [comment]
A sample is a single data point, i.e. a scalar value. A trace is collection of samples at some inline/crossline/offset intersection. The distance between samples are either measured in depth (m/feet/ect..) or time (ms). The slb glossary have entries for these terms

If you are new to seismic/SEGY I suggest that you read up a bit on common terminology and on the SEGY format, as this library and it's documentation assumes that the user is familiar with seismic and SEGY :)
