### ISSUE TITLE
Python version support not updated in setup.py

### ISSUE THREAD

**Issue by berland** [equinor/segyio#545]
README says Python 3.6 is required, setup.py claims 2.7 is supported. Commit history indicates Python 3.11 is supported.

https://github.com/equinor/segyio/blob/a63601d05533342604e3fe48a7edbea767ffe5be/python/setup.py#L107

**Comment by ErlendHaa** [comment]
You are completely right about setup.py, it's highly outdated. README says 3.6 or greater I believe. Which is correct for the current set of prebuilt wheels we distribute. (3.6 - 3.11)

I will update setup.py, thanks!
