### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by mferrera** [equinor/segyio#562]
We would like to add support for Python 3.12 in [equinor/xtgeo](https://github.com/equinor/xtgeo/), however we depend on segyio which currently does not support Python 3.12 🙂

Would it be possible to add support for Python 3.12 for this amazing package? This percolates back upstream to a request from [equinor/ert](https://github.com/equinor/ert/)

(Copied this format downstream from from https://github.com/equinor/xtgeo/issues/995 😄)

**Comment by d-chambers** [comment]
We are also running into this issue in [dascore](github.com/dasdae/dascore). When trying to install it with python 3.12 we get some weird metadata issue that downloads many different segyio versions:
  
![image](https://github.com/equinor/segyio/assets/11671536/178a4341-36eb-407a-b7e5-c6920a11bedd)

**Comment by sveinung-r** [comment]
There is a PR open to build wheels for Python 3.12 #563, but we are currently encountering some issues with the build. We will look into this and distribute for Python 3.12 as soon as possible.

**Comment by d-chambers** [comment]
Great, thanks for all your hard work!

**Comment by sondreso** [comment]
Closed by #563, wheel will be pushed to PyPi on the next release :slightly_smiling_face:
